(TeX-add-style-hook
 "SwiftUI"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "margin=2cm") ("inputenc" "utf8") ("ulem" "normalem") ("babel" "english") ("ctex" "UTF8" "heading") ("sourcecodepro" "default") ("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-environments-local "VerbatimOut")
   (add-to-list 'LaTeX-verbatim-environments-local "SaveVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb*")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings"
    "babel"
    "ctex"
    "xltxtra"
    "xeCJK"
    "lmodern"
    "verbatim"
    "tikz"
    "soul"
    "listing"
    "algorithm"
    "algorithmic"
    "natbib"
    "fancyhdr"
    "fontspec"
    "xunicode"
    "CJKnumb"
    "amsfonts"
    "sourcecodepro"
    "fontenc"
    "color"
    "fancyvrb"
    "placeins"
    "xcolor"
    "enumitem")
   (LaTeX-add-labels
    "sec:orgd284981"
    "sec:orga0c7f6b"
    "sec:org66dae18"
    "sec:orga7610bb"
    "sec:org215195e"
    "sec:org64bf009"
    "sec:orgad6c8bc"
    "sec:orgc451dfa"
    "fig:Diff-1"
    "sec:org62673be"
    "orge908e69"
    "sec:orgbc528df"
    "sec:org9fe8909"
    "sec:org95913a5"
    "orgd6a10cc"
    "sec:orgbd74243"
    "sec:org4ce8ea3"
    "sec:org01f2977"
    "sec:org2b9972e"
    "sec:org68c3f29"
    "sec:org161888f"
    "sec:org9803c3c"
    "sec:orgb96dcbb"
    "sec:org937f96b"
    "sec:org1c99f49"
    "sec:orgad8541d"
    "sec:org04d4e73"
    "sec:org6cf9367"
    "sec:org6cb08be"
    "fig:VStack-1"
    "sec:org6e331c7"
    "sec:orge0454bd"
    "fig:HStack-1"
    "sec:org65d563f"
    "sec:org7c567cf"
    "sec:orgfa6a63c"
    "sec:org840b993"
    "sec:org2da8446"
    "sec:org84db0c0"
    "sec:orge826b5a"
    "fig:Images-1"
    "sec:org516819f"
    "sec:orgc22f537"
    "fig:Images-2"
    "sec:org1a4f104"
    "sec:org412ab74"
    "sec:orgaca7569"
    "sec:orga9ee5fc"
    "fig:Button-1"
    "sec:org46d9d77"
    "sec:orgf3c1d25"
    "sec:org902f09a"
    "sec:org644a968"
    "sec:org800f38c"
    "sec:orge28b386"
    "sec:org4a50ae5"
    "sec:orge491d73"
    "fig:Adv-Text_Attributes"
    "sec:orga1d9ac2"
    "sec:org0b81f33"
    "sec:orgd2e4cf1"
    "fig:Adv-Image-Attributes"
    "sec:org972248d"
    "sec:org6cac3ea"
    "sec:org96017ad"
    "fig:Adv-Button-Attributes"
    "sec:org7f59c97"
    "sec:org920e114"
    "sec:org4a801c4"
    "fig:single-cell"
    "sec:org7d5f204"
    "sec:org80d5bdc"
    "fig:list-1"
    "sec:org84d10fa"
    "sec:org84e1d44"
    "fig:list-2"
    "sec:org14ac36f"
    "sec:org0639967"
    "sec:orgd0d4a2c"
    "fig:list-3"
    "sec:org7179784"
    "sec:org0ff3f7e"
    "fig:Navigation-1"
    "sec:org300b4a8"
    "sec:org1be7984"
    "fig:Background-1"
    "sec:orgd17c297"
    "orgbf6fe03"
    "sec:org8b7cdbf"
    "sec:orgefed3e7"
    "sec:orgfff6d50"
    "sec:orgb60a314"
    "org3a9738d"
    "sec:org7ddd4a7"
    "sec:orgcb30043"
    "sec:org65cc083"
    "sec:org5f98dca"
    "sec:org574b3e1"
    "fig:Structure"
    "sec:org460979b"
    "sec:org90a49b0"
    "fig:Class-1"
    "sec:orgaa61e8f"
    "sec:org294a42e"
    "org5073ec5"
    "fig:MVC"
    "sec:org1efa312"
    "sec:org404fe19"
    "sec:org4e67f78"
    "sec:orgebc97bc"
    "sec:orga6c1aaa"
    "sec:org8760076"
    "sec:org21bca8e"
    "sec:org4531f71"
    "sec:org1b2d3b8"
    "sec:org26fda2f"
    "sec:org861904d"
    "sec:orgbc0e32e"
    "sec:org12368b0"
    "sec:org4447677")
   (LaTeX-add-xcolor-definecolors
    "dkgreen"
    "dred"
    "dblue"
    "lgrey"
    "gray"
    "darkblue"
    "bubbles"
    "foreground"
    "background"
    "preprocess"
    "var"
    "string"
    "type"
    "function"
    "keyword"
    "comment"
    "doc"
    "comdil"
    "constant"))
 :latex)

