(TeX-add-style-hook
 "Swift-Intro"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "utf8") ("ulem" "normalem") ("helvet" "scaled") ("geometry" "margin=2cm" "margin=1.0in") ("natbib" "numbers" "sort&compress" "square") ("babel" "english") ("ctex" "UTF8" "heading") ("sourcecodepro" "default") ("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "SaveVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "VerbatimOut")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb*")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings"
    "titlesec"
    "helvet"
    "courier"
    "natbib"
    "glossaries"
    "setspace"
    "enumitem"
    "babel"
    "ctex"
    "xltxtra"
    "xeCJK"
    "lmodern"
    "verbatim"
    "tikz"
    "soul"
    "algorithm"
    "algorithmic"
    "fancyhdr"
    "fontspec"
    "xunicode"
    "CJKnumb"
    "amsfonts"
    "sourcecodepro"
    "fontenc"
    "color"
    "fancyvrb"
    "placeins")
   (TeX-add-symbols
    "sectionbreak")
   (LaTeX-add-labels
    "basic"
    "resources"
    "sec:org2af8dc5"
    "sec:org291e1f8"
    "variable"
    "sec:org8940d91"
    "sec:orga700b17"
    "sec:org1dd7be1"
    "sec:org8616cfd"
    "sec:org4ad030d"
    "sec:org3afb868"
    "sec:orgf63e217"
    "sec:orgb298e24"
    "sec:orgdd06e93"
    "operation"
    "sec:orgad763be"
    "sec:orgf6498f1"
    "sec:org1937d51"
    "sec:org842e834"
    "sec:orgd8052ca"
    "sec:orgbb61df9"
    "sec:orgf649a0b"
    "observer"
    "sec:org4afd5be"
    "sec:org5514523"
    "flow-control"
    "sec:org9e3e2a3"
    "sec:orgd37d979"
    "sec:orgf527d01"
    "sec:org5628c84"
    "sec:org23186fa"
    "sec:org9b154cc"
    "sec:org1c1fb9f"
    "sec:org508898e"
    "sec:org4c32e1b"
    "sec:org5c41d9f"
    "sec:org7e32753"
    "sec:org1f059a3"
    "sec:orgc8207ab"
    "sec:org83e36ba"
    "sec:org93c6cec"
    "sec:org4a24d44"
    "sec:org3ff7340"
    "set"
    "fig:cts"
    "sec:org98b01e1"
    "sec:org9fa4a54"
    "sec:org10c75bb"
    "sec:org0354b78"
    "sec:org2a8af16"
    "sec:org0caa37a"
    "sec:org8e70efa"
    "orgd84d573"
    "sec:orga577b5c"
    "sec:orga98d58f"
    "sec:orgff31ea9"
    "sec:org478ad15"
    "sec:org541c730"
    "sec:org35effc9"
    "sec:org6f2f509"
    "sec:org20d03b0"
    "sec:orgad1be4b"
    "sec:org15e9c89"
    "sec:orgcc81bd5"
    "function"
    "sec:org534f6bf"
    "sec:org0e1a1e4"
    "sec:org75ff70b"
    "sec:org39029c2"
    "sec:org11e3ab6"
    "sec:org427a1da"
    "sec:org7bdd5c4"
    "sec:org872e3a9"
    "generics"
    "types"
    "sec:org8fe731f"
    "sec:org4ac79ce"
    "sec:org9de8ba5"
    "SW-Struct-Class-Enum"
    "orgefdd4c8"
    "sec:orgbff4f70"
    "sec:orge478b94"
    "sec:org6a101d3"
    "sec:org165f691"
    "sec:org0e2a6f6"
    "sec:org185a97e"
    "sec:org64ea755"
    "sec:org63d32da"
    "sec:org83d41c9"
    "sec:org49ef4c3"
    "org722303a"
    "sec:orgacafb00"
    "sec:org42121fc"
    "sec:org3d724ac"
    "sec:org9f374ed"
    "sec:org82a954b"
    "fig:Structure"
    "sec:org46fe7ef"
    "sec:org43168c6"
    "fig:Class-1"
    "sec:org9cf39f0"
    "sec:org643a976"
    "sec:org245aae1"
    "sec:org06f1a3f"
    "sec:org208e1e8"
    "sec:org4404e3c"
    "sec:org62237d5"
    "sec:orgc8f2bbd"
    "sec:org09d43d8"
    "org16e9493"
    "fig:vt"
    "sec:org19cbdc1"
    "sec:orgb3e4d8b"
    "sec:org87e85cc"
    "org534f006"
    "fig:MVC"
    "sec:orgd65bb6b"
    "protocol")
   (LaTeX-add-color-definecolors
    "dkgreen"
    "dred"
    "dblue"
    "lgrey"
    "gray"
    "darkblue"
    "bubbles"
    "foreground"
    "background"
    "preprocess"
    "var"
    "string"
    "type"
    "function"
    "keyword"
    "comment"
    "doc"
    "comdil"
    "constant"))
 :latex)

