(TeX-add-style-hook
 "testpdf"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "utf8") ("ulem" "normalem") ("helvet" "scaled") ("geometry" "margin=2cm" "margin=1.0in") ("natbib" "numbers" "sort&compress" "square") ("babel" "english") ("ctex" "UTF8" "heading") ("sourcecodepro" "default") ("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-environments-local "VerbatimOut")
   (add-to-list 'LaTeX-verbatim-environments-local "SaveVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb*")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings"
    "titlesec"
    "helvet"
    "courier"
    "natbib"
    "glossaries"
    "setspace"
    "enumitem"
    "babel"
    "ctex"
    "xltxtra"
    "xeCJK"
    "lmodern"
    "verbatim"
    "tikz"
    "soul"
    "algorithm"
    "algorithmic"
    "fancyhdr"
    "fontspec"
    "xunicode"
    "CJKnumb"
    "amsfonts"
    "sourcecodepro"
    "fontenc"
    "color"
    "fancyvrb"
    "placeins")
   (TeX-add-symbols
    "sectionbreak")
   (LaTeX-add-labels
    "SW-UIKIT-SWIFTUI"
    "sec:orga4cf607"
    "sec:orgd553d66"
    "sec:orgb2994eb"
    "sec:org795c661"
    "sec:org6c8a889"
    "sec:org1152a63"
    "sec:org180ab37"
    "sec:org09473c7"
    "fig:Diff-1"
    "sec:org2d49336"
    "org6e0d6a6"
    "sec:orga983aa7"
    "sec:org0f58856"
    "delegate"
    "orge754bad"
    "sec:org6ea8a81"
    "SW-SWIFTUI-INTRO"
    "sec:org4b7eab2"
    "sec:org5250581"
    "sec:org9588e3c"
    "sec:org7fee4bc"
    "sec:org744db64"
    "sec:org7b6d56e"
    "sec:org0e010b6"
    "sec:org53ffea9"
    "sec:org1e2ce89"
    "sec:orgf1b7e0a"
    "sec:org33851b7"
    "fig:VStack-1"
    "sec:org8d2d44a"
    "sec:orgaefab3b"
    "fig:HStack-1"
    "sec:orgc125359"
    "sec:org81c47c9"
    "sec:orge62470a"
    "sec:orga780c9a"
    "sec:org86ea73f"
    "sec:org117187a"
    "sec:org9a28507"
    "sec:org76a1ed3"
    "fig:Images-1"
    "sec:org60182cc"
    "sec:org1696a28"
    "fig:Images-2"
    "sec:org26da57d"
    "sec:orgfdb46cb"
    "sec:org10643f1"
    "sec:orgaa46d5b"
    "sec:orgba4bf40"
    "sec:orgdda8684"
    "org051d2b6"
    "sec:org96763f8"
    "sec:org5aace60"
    "sec:org98fac8e"
    "sec:orgdd6abaa"
    "sec:org4337b15"
    "sec:org43364cf"
    "sec:org1fb718d"
    "fig:Button-1"
    "sec:orgb5b5765"
    "sec:orge5a6ce0"
    "sec:org22a6148"
    "sec:orgd1c095b"
    "sec:org960f1b1"
    "sec:org1b71833"
    "sec:org3fe3f5b"
    "SW-CUSTOMIZED-UI-COMPONENTS"
    "orgcb2dcfe"
    "sec:org0f05844"
    "sec:orgfdf520c"
    "sec:org5854b54"
    "fig:Adv-Text_Attributes"
    "sec:org63422d0"
    "sec:orge1b883e"
    "sec:org2d6d71c"
    "fig:Adv-Image-Attributes"
    "sec:org9efcea3"
    "sec:org01a5569"
    "sec:org7094e6e"
    "fig:Adv-Button-Attributes"
    "sec:orga49927c"
    "sec:org6ea7cce"
    "fig:Background-1"
    "list"
    "sec:org972541c"
    "sec:org153af7c"
    "fig:single-cell"
    "sec:org639c201"
    "sec:org12d87f4"
    "fig:list-1"
    "sec:org37be542"
    "sec:orga2cf338"
    "fig:list-2"
    "sec:orgdc9aca3"
    "sec:orge525699"
    "sec:org327648d"
    "fig:list-3"
    "sec:org765bae4"
    "sec:org7566ced"
    "navigation"
    "sec:org33f68b8"
    "sec:org6084740"
    "sec:orgc0ae716"
    "sec:orgfab2b97"
    "fig:Navigation-1"
    "sec:orgc61ab95"
    "sec:org42a531c"
    "sec:org7a1ef5c"
    "sec:org7b57da3"
    "sec:org78b6083"
    "sec:orge40dfe0"
    "sec:org14dce25"
    "sec:orgef4798d"
    "sec:org0872af8"
    "sec:orgd184cef"
    "sec:org0ebe2d8"
    "passingData"
    "sec:org3cfb184"
    "sec:org7cb7f63"
    "sec:org62d0dc7"
    "SW-MVVM"
    "sec:org537add5"
    "sec:org575d0fd"
    "sec:orgbf21f03"
    "SW-Protocols"
    "sec:org168559a"
    "sec:org14c5e90"
    "sec:org3541a09"
    "sec:org5cbdaac"
    "sec:org05ae121"
    "sec:org2682b20"
    "json"
    "Wrappers"
    "sec:orgb86f12d"
    "sec:org1dcda5a"
    "sec:org7566705"
    "sec:org99949af"
    "sec:org0229f44"
    "sec:orgdcdeb2d"
    "sec:org94d2224"
    "sec:org07e3b83"
    "sec:orgb3d0af5"
    "sec:orgb055367"
    "sec:org79eccfa"
    "sec:org22dd98b"
    "sec:org3c33af9"
    "sec:orgd6b6f1d"
    "sec:orge39177f"
    "sec:org4207e45"
    "sec:orgbf74d30"
    "sec:org2829325"
    "some"
    "sec:orga1b7ef7"
    "sec:org90baca0"
    "sec:org12906b3"
    "sec:org5717d66"
    "userDevaults"
    "sec:org6e5dd53"
    "sec:org54ed363"
    "sec:org1d8e380"
    "advanced")
   (LaTeX-add-color-definecolors
    "dkgreen"
    "dred"
    "dblue"
    "lgrey"
    "gray"
    "darkblue"
    "bubbles"
    "foreground"
    "background"
    "preprocess"
    "var"
    "string"
    "type"
    "function"
    "keyword"
    "comment"
    "doc"
    "comdil"
    "constant"))
 :latex)

